name: AuthMe-AutoConnect-Reloaded
main: me.ilsommo.authmeautoconnect.AuthmeAutoConnect
version: 1.0.0
author: Il Sommo
commands:
  authmeac:
    permission: authmeac.admin
    description: Authme-AutoConnect command.